### ISSUE TITLE
How do we switch instruments

### ISSUE THREAD

**Issue by Matthew1172** [jimutt/osmd-audio-player#102]
I'm using bare javascript and I was thinking I could do something like this
```
audioPlayer.loadScore(osmd);
audioPlayer.setInstrument(new Soundfont.instrument(audioPlayer.ac['_nativeAudioContext'], 'acoustic_grand_piano'), 0);
```
But it doesn't do anything

**Comment by jimutt** [comment]
Hi @Matthew1172 !
`setInstrument()` accepts two parameters, the first being a `voice` object from the score, for which to change instrument, and the second being a numeric MIDI instrument ID.

The set of available voices can be extracted from the osmd sheet like: 
`osmd.Sheet.Instruments.flatMap(i => i.Voices)`

If you want to change the playback instrument for all voices in the score you could do something like:
```Javascript
osmd.Sheet.Instruments
   .flatMap(i => i.Voices)
   .forEach(v => audioPlayer.setInstrument(v, 23))
```

You can use this as a reference for midi instrument IDs:   https://github.com/jimutt/osmd-audio-player/blob/master/src/midi/midiInstruments.ts

**Comment by Matthew1172** [comment]
Thank you so much. This was very helpful for my project.
