### ISSUE TITLE
How can I prevent the screen from following the cursor?

### ISSUE THREAD

**Issue by djae88** [jimutt/osmd-audio-player#17]
in 'vue-player-demo' playing
I don't want the screen to move 
but I can't find any related option

**Comment by jimutt** [comment]
It's configured in the OSMD options on initialization. See this line: https://github.com/jimutt/osmd-audio-player/blob/b92baa3cdd302a981a0c8eb4ca3d13df2d8074e4/demos/vue-player-demo/src/components/Score.vue#L30

**Comment by djae88** [comment]
Thank you for your prompt reply
