### ISSUE TITLE
intrument error

### ISSUE THREAD

**Issue by djae88** [jimutt/osmd-audio-player#19]
When I applied a number of musicxml,

some xml caused error
![sdfsf](https://user-images.githubusercontent.com/56290540/84365353-4971c800-ac0c-11ea-8ebb-0c9da77e358e.png)

and some xml worked well

so I looked at the similarities and I found that

working well xml use &lt;instrument-name&gt;Piano&lt;/instrument-name&gt;
![image](https://user-images.githubusercontent.com/56290540/84365571-98b7f880-ac0c-11ea-81f8-9829930c2de6.png)

and others use something else
![image](https://user-images.githubusercontent.com/56290540/84365652-bbe2a800-ac0c-11ea-9692-45fa3081954d.png)
![image](https://user-images.githubusercontent.com/56290540/84365969-2eec1e80-ac0d-11ea-8dbe-b43b1aff58ed.png)

![image](https://user-images.githubusercontent.com/56290540/84366016-3ca1a400-ac0d-11ea-913b-25aa579d6875.png)
no errors have occurred since it was overwritten

I think if instrument-name is not in list (available instrument list?)
It seems to be causing an error

so I think adding 
if instument-name in xml is not in list 
then overwrite piano or similar instrument(available)
will solve the error

thanks for reading

**Comment by jimutt** [comment]
Thank you, I'll look into it! Would be great if you could perhaps send me one of the problematic music xml files. (link here or to email to  jimmy@utterstrom.xyz)

**Comment by djae88** [comment]
I emailed you two files that had a problem

best wishes

**Comment by jimutt** [comment]
Thank you! 
I've got a PR ready with the changes required for performing a fallback to grand piano whenever there's an attempt to load an unknown or non-supported instrument. 

In the two example scores there are no `<midi-intrument>` information available in the XML. Although OSMD had still assigned a MIDI instrument ID (not the correct one for one of the scores though, so not sure how that instrument assignment is handled internally in OSMD when the midi information is not available). 

In one of the files it also sounded like a few notes was missed during playback, I'll investigate that separately though.

**Comment by djae88** [comment]
Thank you so much, 
I didn't realize about the missing note
I'm looking forward to a new update.

**Comment by jimutt** [comment]
@djae88 should hopefully work with the 0.5.0 version now
