### ISSUE TITLE
The cursor cannot follow the new page.

### ISSUE THREAD

**Issue by djae88** [jimutt/osmd-audio-player#22]
![image](https://user-images.githubusercontent.com/56290540/84872150-7a467700-b0bc-11ea-90a6-87c702c4e153.png)

this project work well when pageformat is endless
but when I set pageformat option (or newPageFromXML option) like "a4 p" or others
cursor cannot follow the new page 
it came back to starting point (but it wasn't an exact location)

![image](https://user-images.githubusercontent.com/56290540/84872124-70bd0f00-b0bc-11ea-8fbb-984ef9d97dd6.png)

![image](https://user-images.githubusercontent.com/56290540/84872096-6438b680-b0bc-11ea-917d-7b173a50fb3f.png)

Thanks

**Comment by jimutt** [comment]
Hi! 
I've confirmed that this issue exists with the latest OSMD version, and also if the same options are used in the basic demo project. But these page format options are part of the OSMD library. And also the cursor/iterator control. So I would recommend you to report your findings as an issue in the Open Sheet Music display repository instead.

**Comment by sschmidTU** [comment]
This was an OSMD issue, and was fixed in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/817.
The fix should be included in OSMD 0.8.4 (which should be coming soon).

**Comment by sschmidTU** [comment]
OSMD 0.8.4 is released now with the fix for this, so maybe @jimutt update package.json to OSMD 0.8.4?
(it's at 0.7.3 right now, should be a lot of nice improvements. i hope it's not much of a hassle to update!)

**Comment by jimutt** [comment]
@sschmidTU Ah, that's great. Absolutely, will bump the OSMD dependency to 0.8.4 and push a new version when I'm able (on Tuesday or Wednesday).

**Comment by jimutt** [comment]
Now the dependency has been updated, and released as 0.6.1
