### ISSUE TITLE
Need more detailed documentation

### ISSUE THREAD

**Issue by netbeifeng** [jimutt/osmd-audio-player#31]
Hello there!
Thank you very much for developing this plugin. This feature is exactly what I need! (for hexo blog)
But I am confused, how can I use it?

Obviously write directly in html:
```html
<script src="./app.js"></script>
```
Is not working.

So I hope to have a more detailed introduction on how users should use it after installation.
Thank you!

Best wishes
Chang

**Comment by netbeifeng** [comment]
use 
```bash
npm run build
```
get app.min.js in dist

**Comment by sschmidTU** [comment]
clarification: either run `npm run build` in demos/basic or demos/vue (and run `npm install` there beforehand),
or in the main folder, run `npm install` and `npm run netlify-build` in the main folder.
the app.*.js will be in the demos/basic and demos/vue folders.
