### ISSUE TITLE
Future binary?

### ISSUE THREAD

**Issue by matty90278** [jimutt/osmd-audio-player#37]
Hi,
I have written an ios app using OSMD. It uses a WKWebview but all files are loaded locally. I would love to incorporate your audio player. I have just started to experiment with it. I can run the basic demo locally but am trying to figure out how I am going to add this to my XCode project.

Do you think it may be possible for you to provide a master binary in your future releases? I don't know Javascript well so am not sure if this is practical. But with OSMD, I just add the binary opensheetmusicdisplay.min.js to the project and I can easily reference everything using that and get it all to work. With the audio player, importing and connecting all of the various parts of the project (../../dist/PlaybackEngine, etc.) make it relatively complicated and impractical for an app development situation. 
Please let me know if the binary idea makes sense and is a possibility. I would appreciate any advice otherwise.
Thank you!
Matt

**Comment by ilionic** [comment]
Interesting question. Not that I have good answer ( nor am I maintainer ) but doing something similar from a bit different perspective - mainly to learn iOS dev (from JS background) and overcome some Web limitations ( such as iOS midi I/O and use more robust audio frameworks ). 

What I am currently working on is to receive a midi message from OSMD web view to native and handle audio playback using [AudioKit](https://audiokit.io/). It's robust and doesn't have usual single threaded web audio problems.
Curious how you are handling passing XML files between native context and web view.

**Comment by jimutt** [comment]
Hi, sorry for the delay! You have to correct me if I'm wrong @matty90278, but if I understand you correctly your mainly after a single bundled distribution of the audio player that can be used in the same style as the opensheetmusicdisplay.min.js you mentioned? You're not looking to integrate it with native code in the iOS app?

In case you're just after a bundled distribution in the same fashion as OSMD is offering it's absolutely something I can fix, and that I've also planned. The current build exports modern Javascript using ES modules. But I do also plan to fix a more standard old-fashioned build to be easily referenced in an web page, also with better support for slightly older browsers. 

I've got a similar request by email previously, so I'll look into doing this rather soon.

**Comment by jimutt** [comment]
@matty90278 There is now a minified UMD build available. See the updated README. It can be downloaded through JSDelivr at: https://cdn.jsdelivr.net/npm/osmd-audio-player/umd/OsmdAudioPlayer.min.js

**Comment by matty90278** [comment]
> @matty90278 There is now a minified UMD build available. See the updated README. It can be downloaded through JSDelivr at: https://cdn.jsdelivr.net/npm/osmd-audio-player/umd/OsmdAudioPlayer.min.js

Hi,
Yes, that is exactly what I was asking for. Thank you!! I got it running in my iOS app. I haven’t tested thoroughly yet and there are some error messages (I think they are Apple bugs) but I think this approach will work for me.

I’ll have to look through your files more but do you have any simple guides to turning on/off settings yet? For instance, is there a feature to have a cursor track through the music as it is played?

I look forward to the future updates. Thanks again for the quick response!
