### ISSUE TITLE
The rest note makes a sound

### ISSUE THREAD

**Issue by djae88** [jimutt/osmd-audio-player#41]
The rest note's supposed to be silent, but
when the display-step and display-octave is set and
it is lower than octave 5, D
this makes a sound.

this sample is made of four rest notes.
first rest note 
![image](https://user-images.githubusercontent.com/56290540/94624858-5bc65d80-02f2-11eb-89b4-ff5e2d7a77ec.png)
Second rest note (this note makes a sound)
![image](https://user-images.githubusercontent.com/56290540/94624901-7698d200-02f2-11eb-829f-e7618fe91fa9.png)
third rest note (this note makes a sound)
![image](https://user-images.githubusercontent.com/56290540/94624932-8a443880-02f2-11eb-8d7c-31180d2b8c66.png)
fourth rest note
![image](https://user-images.githubusercontent.com/56290540/94624976-a051f900-02f2-11eb-8054-3e3fa0f2fc5b.png)

The sample: 
![image](https://user-images.githubusercontent.com/56290540/94625218-2d954d80-02f3-11eb-98c9-edd86b836960.png)
[test rest note sound.zip](https://github.com/jimutt/osmd-audio-player/files/5302274/test.rest.note.sound.zip)

Best Wishes, Thanks

**Comment by jimutt** [comment]
Thanks for the report! This was definitely interesting and worth looking into. A classic example of "it's a feature, not a bug" 😉

**Comment by sschmidTU** [comment]
I think this may be because OSMD sometimes assigns a rest note a pitch, so that it is positioned differently in the score.
I guess you could just check if the note is a rest (`graphicalNote.sourceNote.isRest()`), and if so, don't play it.

**Comment by sschmidTU** [comment]
Or play it with 0 volume, if you want the timing information

**Comment by jimutt** [comment]
I believe the little fix in #50 should solve this, it at least did so for some of my own scores with this problem.
