### ISSUE TITLE
Adding score XML string in demo does not show cursor

### ISSUE THREAD

**Issue by infojunkie** [jimutt/osmd-audio-player#42]
For a quick test, I am replacing https://github.com/jimutt/osmd-audio-player/blob/master/demos/umd-web/app.js#L5-L7 with something like:
```
const scoreXml = `
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
 <!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
 <score-partwise version="3.1">
   <movement-title>Chord Symbol Example</movement-title>
   <identification>
   [...]
`.trim();
```
which puts the XML straight into the demo source. The [XML file is here](https://wpmedia.musicxml.com/wp-content/uploads/2017/12/chord.musicxml).

The sheet gets displayed properly, and I can play it, but the green cursor does not show or advance. What am I missing? Thanks!

**Comment by matty90278** [comment]
Maybe there are a couple instructions left undone in the UMD. I had to add 
audioPlayer.cursor.show();
to my code to get the cursor to show but it still doesn't advance.

**Comment by infojunkie** [comment]
Thanks! It's just weird that it works correctly on the example, downloaded file. I'll dig more when I get the chance.

**Comment by matty90278** [comment]
@jimutt I am in Xcode and I get the following errors when I run with the audio player. Maybe this has something to do with the cursor display problem? It plays the audio fine.
<img width="1023" alt="Screen Shot 2020-10-01 at 7 44 32 AM" src="https://user-images.githubusercontent.com/66330747/94825159-ae6b4c80-03ba-11eb-906a-4539038ebb45.png">

**Comment by jimutt** [comment]
@infojunkie Thanks, I'll look into it too. I've been having occasional issues a bit now and then with the cursor visibility though and I think it's closer to OSMD than it is to the audio player. I'll see if I figure it out anyhow.

**Comment by jimutt** [comment]
@matty90278  My Xcode and native iOS development skills are unfortunately very close to zero. But in the error message you showed I see nothing that seems related to the actual audioplayer. I'm able to find some similar error reports for other software and libraries though. It seems more platform related (iOS, Webkit, webview):

https://bugs.webkit.org/show_bug.cgi?id=204261
https://github.com/Scirra/Construct-3-bugs/issues/3477

**Comment by sschmidTU** [comment]
@matty90278 your app doesn't have the necessary entitlements (authorizations to use certain features of the phone set), namely MediaPlayback.
https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AboutEntitlements.html
(This Apple documentation is, as usual, not very helpful. You probably need to modify your Entitlements.plist)

**Comment by taerilan** [comment]
Hi there,

We've also noticed there are issues with cursor following the played note when playing .xml file, but didn't encounter that issue while playing .mxl filled, maybe that helps
