### ISSUE TITLE
Error with ionic 

### ISSUE THREAD

**Issue by Fabryzya** [jimutt/osmd-audio-player#44]
Hi guys,
I find to use library with my ionic app
pakage.json 
{
  "name": "SolfeggioApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular-devkit/schematics": "^10.2.0",
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@capacitor/core": "2.4.0",
    "@ionic-native/core": "4.20.0",
    "@ionic-native/device": "^5.29.0",
    "@ionic-native/media": "^5.29.0",
    "@ionic-native/native-audio": "^5.29.0",
    "@ionic-native/splash-screen": "4.20.0",
    "@ionic-native/status-bar": "4.20.0",
    "@ionic/storage": "2.2.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^6.0.0",
    "@types/node": "^14.14.5",
    "ionic-angular": "3.9.9",
    "ionicons": "3.0.0",
    "osmd-angular": "^1.0.3",
    "osmd-audio-player": "^0.6.2",
    "rxjs": "^5.5.11",
    "soundfont-player": "^0.12.0",
    "standardized-audio-context": "^25.1.4",
    "sw-toolbox": "3.6.0",
    "typescript": "^4.0.3",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@capacitor/cli": "2.4.0",
    "@ionic/app-scripts": "3.2.4",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-nativeaudio": "^3.0.9"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-nativeaudio": {},
      "cordova-plugin-device": {}
    }
  }
}
In a component I use library in this way: 
import { PlaybackEvent } from 'osmd-audio-player/src/PlaybackEngine';
import AudioPlayer  from 'osmd-audio-player/src';
.....
 ngAfterViewInit() {
    try {
      const canvas: HTMLElement = document.getElementById("score");
      this.openSheetMusicDisplay = new OpenSheetMusicDisplay(canvas);
      this.openSheetMusicDisplay.setLogLevel('error');
      this.openSheetMusicDisplay
        .load("../../assets/esercizi/dettati/livello_base/esercizio_1/Dettato_Melodico_Esercizio1_music_xml.xml")
        .then(
          () =>
            this.init(),
          (err) => console.error(err)
        )
        .then(
          () => console.log("Sheet music displayed."),
          (err) => console.error(err)
        );
    } catch (e) {
      console.error(e);
    }

  }

  async init() {
    this.openSheetMusicDisplay.render();
    const audioPlayer = new AudioPlayer();
    await audioPlayer.loadScore(this.openSheetMusicDisplay);
    audioPlayer.on(PlaybackEvent.ITERATION, notes => {
      console.log(notes);
    });
  }
and got this error:
Error: Module build failed: Error: ENOENT: no such file or directory, open '....\node_modules\osmd-audio-player\src\PlaybackEngine.js'

Please Do you know why?
Thanks

**Comment by lhl2617** [comment]
Seems to be a 0.6.2 issue. Bumping back down to 0.6.1 fixes it. I'm affected by this and will look into this if @jimutt  needs help

**Comment by Fabryzya** [comment]
Thank you @lhl2617 . 
Ionic it's very hard to debug when there are build errors. 
I resolved in another way.
My problems was two:
1) Version of typescript not compatible with Ionic
2) Library used for AudioPlayer not compatible with mobile devices.
I rewrote some parts of osmd for use it and added some configuration for  audio.
Now I have problem with metronome sound.
Do you know if it is possible to reproduce this sound?
Thank you very much, for your support.
Fabrizia

**Comment by jimutt** [comment]
Hi! 
Sorry for the build issues on 0.6.2. You can give it a go with 0.6.3 now @Fabryzya & @lhl2617  🙂 

I've been a bit less active here lately due to having much to do at my normal job, but also since I have been involved some in the upcoming official OSMD audio player. So things are moving along on the OSMD audio side, just not a lot in this repo 🙂

**Comment by jimutt** [comment]
>  Do you know if it is possible to reproduce this sound?
Are you wondering how to find/create a suitable sound for the metronome? I know that it's quite common to just utilize existing sounds from midi drums. Otherwise, I assume you'll have to handle the metronome separately or use a modified soundfont where you have a dedicated metronome sound available.
