### ISSUE TITLE
Get time

### ISSUE THREAD

**Issue by RokUrbancX** [jimutt/osmd-audio-player#49]
Is there a way to get the exact time of note(and NoteTie)?

I tried to get it from OsmdAudioPlayer.min.js it works for all except ties.

**Comment by sschmidTU** [comment]
@RokUrbancX did you solve the problem?

**Comment by RokUrbancX** [comment]
I did, thanks anyway :) 
`time = notes [I]. Length. realValue*t;`

And then I did check if the note is tied & first tie and if I added it to current total time.

**Comment by sschmidTU** [comment]
Cool, thanks for leaving the solution for anyone who might look for it!
