### ISSUE TITLE
Scheduler question

### ISSUE THREAD

**Issue by ilionic** [jimutt/osmd-audio-player#6]
Hey just a question not really an issue. 
Trying to investigate general principles and design. 
Do I understand correctly scheduler implementation is mainly to correctly playback audio?
I am looking into how possible to make something like step sequencer but without audio ( just getting current note info ). Is it simply achievable or calculating audio context related timestamps embedded and part of scheduler / iteration?
Thank you! Code looking clean, wish better understand it. 

edit: just discovered https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Tutorial:-Extracting-note-timing-for-playing - is it based on such concepts?

**Comment by jimutt** [comment]
Yes, the scheduler's main compelxity is there to schedule playback in advance to reduce the risk of playback issues. 

If you only want to step through the score you can make do with the built-in iterator from OSMD. In the playback engine class you'll find: 
````Typescript
private countAndSetIterationSteps() {
    this.cursor.reset();
    let steps = 0;
    while (!this.cursor.Iterator.EndReached) {
      if (this.cursor.Iterator.CurrentVoiceEntries) {
        this.scheduler.loadNotes(this.cursor.Iterator.CurrentVoiceEntries);
      }
      this.cursor.next();
      ++steps;
    }
    this.iterationSteps = steps;
    this.cursor.reset();
  }
```

The cursor is from the OSMD instance and contains the iterator that iterates through the whole score. For each iteration step you can access all the voice entries under the cursor through `cursor.Iterator.CurrentVoiceEntries`. Which should be enough for your use case I reckon.  

You'll find the individual music notes by iterating over the voice entries:
```Typescript
for (let entry of currentVoiceEntries) {
      for (let note of entry.Notes) {
        this.loaderFutureTicks.add(thisTick + note.Length.RealValue * this.tickDenominator);
        this.stepQueue.add(thisTick, note);
      }
    }
```

**Comment by ilionic** [comment]
Thanks a lot for your effort explaining
